# Generated by Django 5.0.8 on 2024-08-14 10:57

import django.db.models.deletion
import django.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('unique_code', models.CharField(default=django.utils.crypto.get_random_string, max_length=20, unique=True)),
                ('expired', models.BooleanField(default=False)),
                ('canceled', models.BooleanField(default=False)),
                ('day_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.dayschedule')),
            ],
        ),
    ]
